# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db079333b6920212ac7b0b688b75b938240e4b30ebbf88a76587ce155487e5177613caa74c3ae3e079304106ee32f62bdd6ea5d64332846ebb2318888f688ce4

test:
  secret_key_base: 52491711b9a3014e726dcc2347ccd89bde3932a09285da4a1e43b2b816e27599dbdca0d21ae07b44c1d021dd317d807ebc36c5bcbdde3b950d47d0a1d77a2a0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
